services:
  surstock:
    build: .
    container_name: surstock
    expose:
      - "3001"
    environment:
      - DB_DIR=/app/backend/data
      - ADMIN_PASSWORD_HASH=21a7d2207af0e4b7f595e85eff6861732df082461584b89f6c68bbfaacb67f59
      - STORE_PASSWORD_HASH=add9d8e85ec12c577abcbed5a6080bb4804add72766f898d200951333b58552c
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.surstock.rule=Host(`sur-stock.myorigines.tech`)"
      - "traefik.http.routers.surstock.entrypoints=websecure"
      - "traefik.http.routers.surstock.tls.certresolver=letsencrypt"
      - "traefik.http.services.surstock.loadbalancer.server.port=3001"
    volumes:
      - surstock-data:/app/backend/data
    restart: unless-stopped
    networks:
      - myorigines-network

volumes:
  surstock-data:

networks:
  myorigines-network:
    external: true
